// src/ipc/channels.ts
export const CHANNELS = {
    LOAD_STATE: 'LOAD_STATE',
    SAVE_STATE: 'SAVE_STATE',
    LOAD_SETTINGS: 'LOAD_SETTINGS',
    SAVE_SETTINGS: 'SAVE_SETTINGS',
    GET_ATLASSIAN_SECRET: 'GET_ATLASSIAN_SECRET',
    ZEPHYR_GET_TESTCASE: 'ZEPHYR_GET_TESTCASE',
    ZEPHYR_SEARCH_TESTCASES: 'ZEPHYR_SEARCH_TESTCASES',
    ZEPHYR_UPSERT_TESTCASE: 'ZEPHYR_UPSERT_TESTCASE',
    WRITE_STATE_SNAPSHOT: 'WRITE_STATE_SNAPSHOT',
    WRITE_PUBLISH_LOG: 'WRITE_PUBLISH_LOG',
} as const
