export const CHANNELS = {
    LOAD_STATE: 'LOAD_STATE',
    SAVE_STATE: 'SAVE_STATE',
    LOAD_SETTINGS: 'LOAD_SETTINGS',
    SAVE_SETTINGS: 'SAVE_SETTINGS',
    GET_ATLASSIAN_SECRET: 'GET_ATLASSIAN_SECRET',
} as const
