// src/ipc/channels.ts
export const CHANNELS = {
    LOAD_STATE: 'LOAD_STATE',
    SAVE_STATE: 'SAVE_STATE',
    LOAD_SETTINGS: 'LOAD_SETTINGS',
    SAVE_SETTINGS: 'SAVE_SETTINGS',
    GET_ATLASSIAN_SECRET: 'GET_ATLASSIAN_SECRET',
    ZEPHYR_GET_TESTCASE: 'ZEPHYR_GET_TESTCASE',
} as const
