import * as React from 'react'

export type UiLocale = 'ru' | 'en'
export type UiThemeMode = 'light' | 'dark'

const LOCALE_STORAGE_KEY = 'ui.locale'
const THEME_STORAGE_KEY = 'ui.theme'

const messages = {
    ru: {} as Record<string, string>,
    en: {} as Record<string, string>,
}

Object.assign(messages.ru, {
    'app.loading': 'Загрузка...',
    'app.loadingEditor': 'Загрузка редактора...',
    'toast.changesSaved': 'Изменения сохранены',
    'toast.selectCaseBeforeExport': 'Перед экспортом выберите кейс',
    'toast.exportOnlyForCase': 'Экспорт доступен только для тест-кейса',
    'toast.caseExported': 'Кейс экспортирован в JSON',
    'toast.importApplied': 'Импорт завершён: создано {created}, обновлено {updated}, черновиков {drafts}, пропущено {skipped}',
    'toast.publishFinished': 'Публикация завершена: создано {created}, обновлено {updated}, ошибок {failed}. Снимок: {snapshotPath}. Лог: {logPath}',

    'toolbar.editor': 'Редактор',
    'toolbar.importTarget': 'Цель импорта: {label}',
    'toolbar.publishScopeEmpty': 'Область публикации пуста',
    'toolbar.publishScopeLabel': 'Область публикации: {label}',
    'toolbar.publishScopeCount': 'Область публикации: кейсов {count}',
    'toolbar.local': 'Локально',
    'toolbar.panels': 'Панели',
    'toolbar.save': 'Сохранить',
    'toolbar.saveTitle': 'Сохранить (Ctrl+S)',
    'toolbar.newCase': 'Новый кейс',
    'toolbar.newFolder': 'Новая папка',
    'toolbar.preview': 'Предпросмотр',
    'toolbar.raw': 'Исходник',
    'toolbar.previewTitle': 'Переключить режим просмотра для текущего кейса',
    'toolbar.syncCenter': 'Центр синхронизации',
    'toolbar.hideSync': 'Скрыть синхронизацию',
    'toolbar.syncCenterTitle': 'Открыть отдельную рабочую зону синхронизации',
    'toolbar.more': 'Ещё',
    'toolbar.moreTitle': 'Дополнительные действия',
    'toolbar.moreMenu': 'Дополнительные действия',
    'toolbar.exportJson': 'Экспорт JSON',
    'toolbar.exportJsonHint': 'Скачать текущий кейс как JSON',
    'toolbar.deleteSelection': 'Удалить выбор',
    'toolbar.deleteSelectionHint': 'Удалить текущий кейс или папку',
    'toolbar.settings': 'Настройки',
    'toolbar.settingsHint': 'Открыть интеграции и настройки приложения',

    'overview.casesInScope': 'Кейсов в области',
    'overview.casesInScopeHint': 'Будут участвовать в пакетной публикации',
    'overview.importFromZephyr': 'Импорт из Zephyr',
    'overview.importFromZephyrDescription': 'Подтянуть кейсы в выбранную папку с предварительным просмотром изменений.',
    'overview.publishToZephyr': 'Публикация в Zephyr',
    'overview.publishToZephyrDescription': 'Сравнить локальные кейсы с Zephyr и отправить подтверждённый пакет изменений.',
    'overview.openImport': 'Открыть импорт...',
    'overview.openPublish': 'Открыть публикацию...',
    'overview.newFolder': 'Новая папка',
    'overview.newCase': 'Новый кейс',
    'overview.syncCenter': 'Центр синхронизации',
    'overview.zephyrWorkspace': 'Пространство Zephyr',

    'sync.importTarget': 'Цель импорта',
    'sync.importTargetHint': 'Импортированные кейсы попадут сюда, если не менять область.',
    'sync.publishScope': 'Область публикации',
    'sync.publishScopeHint': 'Выбранные кейсы будут показаны в dry-run перед записью.',
    'sync.importFromZephyr': 'Импорт из Zephyr',
    'sync.publishToZephyr': 'Публикация в Zephyr',
    'sync.pullCurrent': 'Подтянуть текущий кейс',
    'sync.quickSync': 'Быстрая синхронизация',
    'sync.close': 'Закрыть',

    'tree.navigator': 'Навигатор',
    'tree.cases': 'Кейсы',
    'tree.keyboardHint': 'Стрелки двигают фокус, Enter открывает, Shift+F10 показывает действия.',
    'tree.folder': 'Папка',
    'tree.case': 'Кейс',
    'tree.itemCount': 'Элементов: {count}',
    'tree.stepCount': 'Шагов: {count}',
    'tree.noSteps': 'Шагов пока нет',
    'tree.untitledStep': 'Шаг без названия',
    'tree.untitled': 'Без названия',
    'tree.sharedRef': 'общая ссылка',
    'tree.subCount': 'подшагов: {count}',
    'tree.fileCount': 'файлов: {count}',
    'tree.treeActions': 'Действия дерева',
    'tree.newFolder': 'Новая папка',
    'tree.newCase': 'Новый кейс',
    'tree.rename': 'Переименовать',
    'tree.delete': 'Удалить',
    'tree.renamePlaceholder': 'Переименовать...',
    'tree.openActions': 'Открыть действия для {name}',
    'tree.openStepTitle': 'Открыть этот шаг в редакторе',
    'tree.folderTitle': 'Папка',
    'tree.caseTitle': 'Тест-кейс',
    'tree.expand': 'Развернуть',
    'tree.collapse': 'Свернуть',
    'tree.noNestedItems': 'Нет вложенных элементов',
    'tree.sync.conflict': 'Конфликт',
    'tree.sync.synced': 'Синхронизирован',
    'tree.sync.dirtyTitle': 'Есть локальные изменения, не синхронизированные с удалённой системой',

    'editor.testCase': 'Тест-кейс',
    'editor.previewAll': 'Предпросмотр всего',
    'editor.rawAll': 'Исходный текст всего',
    'editor.hideLibrary': 'Скрыть библиотеку',
    'editor.libraryCount': 'Библиотека ({count})',
    'editor.name': 'Название',
    'editor.namePlaceholder': 'Введите название тест-кейса...',
    'editor.summary.steps': 'Шаги: {count}',
    'editor.summary.sharedRefs': 'Общих ссылок: {count}',
    'editor.summary.attachments': 'Вложений: {count}',
    'editor.summary.tags': 'Тегов: {count}',
    'editor.summary.linkedZephyr': 'Есть связь с Zephyr',
    'editor.summary.linkedAllure': 'Есть связь с Allure',
    'editor.details': 'Описание',
    'editor.parameters': 'Параметры',
    'editor.attachments': 'Вложения',
    'editor.integrations': 'Интеграции',
    'editor.sharedLibraryDrawer': 'Панель библиотеки общих шагов',
    'editor.close': 'Закрыть',
    'editor.zephyrKey': 'Ключ Zephyr',
    'editor.zephyrKeyPlaceholder': 'Например: PROD-T6079 или 6079',
    'editor.allureId': 'ID Allure',
    'editor.allureIdPlaceholder': 'Например: 12345',
    'editor.sectionExpand': 'Развернуть раздел',
    'editor.sectionCollapse': 'Свернуть раздел',

    'settings.title': 'Настройки',
    'settings.close': 'Закрыть',
    'settings.tab.atlassian': 'Синхронизация Atlassian',
    'settings.tab.appearance': 'Внешний вид',
    'settings.loading': 'Загрузка…',
    'settings.saved': 'Сохранено в системное хранилище',
    'settings.saveError': 'Не удалось сохранить. Попробуйте ещё раз.',
    'settings.atlassianTitle': 'Синхронизация Atlassian',
    'settings.baseUrl': 'Базовый URL Atlassian',
    'settings.login': 'Логин Atlassian',
    'settings.password': 'Пароль',
    'settings.passwordStored': 'сохранён',
    'settings.passwordPlaceholder': '•••••• (нажмите на глаз, чтобы показать, или введите новый для замены)',
    'settings.hide': 'Скрыть',
    'settings.show': 'Показать',
    'settings.hidePassword': 'Скрыть пароль',
    'settings.showPassword': 'Показать пароль',
    'settings.securityHint': 'Логин и базовый URL сохраняются в .settings.json внутри репозитория, а секрет хранится в системном защищённом хранилище.',
    'settings.save': 'Сохранить',
    'settings.appearanceTitle': 'Внешний вид',
    'settings.language': 'Язык интерфейса',
    'settings.theme': 'Тема',
    'settings.languageHint': 'Универсальные элементы интерфейса переключаются между языками без изменения самих тестов.',
    'settings.themeHint': 'Тёмная тема применяется ко всему интерфейсу редактора и модалкам.',
    'settings.language.ru': 'Русский',
    'settings.language.en': 'English',
    'settings.theme.light': 'Светлая',
    'settings.theme.dark': 'Тёмная',

    'defaults.newFolder': 'Новая папка',
    'defaults.newCase': 'Новый кейс',
    'defaults.firstStep': 'Шаг 1',
    'defaults.sharedStep': 'Общий шаг',
})

Object.assign(messages.en, {
    'app.loading': 'Loading...',
    'app.loadingEditor': 'Loading editor...',
    'toast.changesSaved': 'Changes saved',
    'toast.selectCaseBeforeExport': 'Select a case before export',
    'toast.exportOnlyForCase': 'Export works only for a test case',
    'toast.caseExported': 'Case exported to JSON',
    'toast.importApplied': 'Import applied: {created} created, {updated} updated, {drafts} drafts, {skipped} skipped',
    'toast.publishFinished': 'Publish finished: {created} created, {updated} updated, {failed} failed. Snapshot: {snapshotPath}. Log: {logPath}',

    'toolbar.editor': 'Editor',
    'toolbar.importTarget': 'Import target: {label}',
    'toolbar.publishScopeEmpty': 'Publish scope is empty',
    'toolbar.publishScopeLabel': 'Publish scope: {label}',
    'toolbar.publishScopeCount': 'Publish scope: {count} cases',
    'toolbar.local': 'Local',
    'toolbar.panels': 'Panels',
    'toolbar.save': 'Save',
    'toolbar.saveTitle': 'Save (Ctrl+S)',
    'toolbar.newCase': 'New Case',
    'toolbar.newFolder': 'New Folder',
    'toolbar.preview': 'Preview',
    'toolbar.raw': 'Raw',
    'toolbar.previewTitle': 'Toggle preview mode for the current case',
    'toolbar.syncCenter': 'Sync Center',
    'toolbar.hideSync': 'Hide Sync',
    'toolbar.syncCenterTitle': 'Open the separate sync workspace',
    'toolbar.more': 'More',
    'toolbar.moreTitle': 'More actions',
    'toolbar.moreMenu': 'More actions',
    'toolbar.exportJson': 'Export JSON',
    'toolbar.exportJsonHint': 'Download the current case as JSON',
    'toolbar.deleteSelection': 'Delete selection',
    'toolbar.deleteSelectionHint': 'Remove the current case or folder',
    'toolbar.settings': 'Settings',
    'toolbar.settingsHint': 'Open integrations and app settings',

    'overview.casesInScope': 'Cases in scope',
    'overview.casesInScopeHint': 'Will participate in batch publish',
    'overview.importFromZephyr': 'Import from Zephyr',
    'overview.importFromZephyrDescription': 'Pull cases into the selected folder with a preview-first review flow.',
    'overview.publishToZephyr': 'Publish to Zephyr',
    'overview.publishToZephyrDescription': 'Compare local cases with Zephyr and send a confirmed batch of changes.',
    'overview.openImport': 'Open import...',
    'overview.openPublish': 'Open publish...',
    'overview.newFolder': 'New Folder',
    'overview.newCase': 'New Case',
    'overview.syncCenter': 'Sync Center',
    'overview.zephyrWorkspace': 'Zephyr workspace',

    'sync.importTarget': 'Import target',
    'sync.importTargetHint': 'Imported cases land here unless you change scope.',
    'sync.publishScope': 'Publish scope',
    'sync.publishScopeHint': 'Selected cases appear in a dry-run before any write.',
    'sync.importFromZephyr': 'Import from Zephyr',
    'sync.publishToZephyr': 'Publish to Zephyr',
    'sync.pullCurrent': 'Pull current case',
    'sync.quickSync': 'Quick sync',
    'sync.close': 'Close',

    'tree.navigator': 'Navigator',
    'tree.cases': 'Cases',
    'tree.keyboardHint': 'Arrows move focus, Enter opens, Shift+F10 shows actions.',
    'tree.folder': 'Folder',
    'tree.case': 'Case',
    'tree.itemCount': 'Items: {count}',
    'tree.stepCount': 'Steps: {count}',
    'tree.noSteps': 'No steps yet',
    'tree.untitledStep': 'Untitled step',
    'tree.untitled': 'Untitled',
    'tree.sharedRef': 'shared ref',
    'tree.subCount': 'substeps: {count}',
    'tree.fileCount': 'files: {count}',
    'tree.treeActions': 'Tree actions',
    'tree.newFolder': 'New Folder',
    'tree.newCase': 'New Case',
    'tree.rename': 'Rename',
    'tree.delete': 'Delete',
    'tree.renamePlaceholder': 'Rename...',
    'tree.openActions': 'Open actions for {name}',
    'tree.openStepTitle': 'Open this step in the editor',
    'tree.folderTitle': 'Folder',
    'tree.caseTitle': 'Test case',
    'tree.expand': 'Expand',
    'tree.collapse': 'Collapse',
    'tree.noNestedItems': 'No nested items',
    'tree.sync.conflict': 'Conflict',
    'tree.sync.synced': 'Synced',
    'tree.sync.dirtyTitle': 'Local changes are not synced with the remote system',

    'editor.testCase': 'Test case',
    'editor.previewAll': 'Preview All',
    'editor.rawAll': 'Raw All',
    'editor.hideLibrary': 'Hide Library',
    'editor.libraryCount': 'Library ({count})',
    'editor.name': 'Name',
    'editor.namePlaceholder': 'Enter test case name...',
    'editor.summary.steps': 'Steps: {count}',
    'editor.summary.sharedRefs': 'Shared refs: {count}',
    'editor.summary.attachments': 'Attachments: {count}',
    'editor.summary.tags': 'Tags: {count}',
    'editor.summary.linkedZephyr': 'Linked to Zephyr',
    'editor.summary.linkedAllure': 'Linked to Allure',
    'editor.details': 'Details',
    'editor.parameters': 'Parameters',
    'editor.attachments': 'Attachments',
    'editor.integrations': 'Integrations',
    'editor.sharedLibraryDrawer': 'Shared library drawer',
    'editor.close': 'Close',
    'editor.zephyrKey': 'Zephyr key',
    'editor.zephyrKeyPlaceholder': 'Example: PROD-T6079 or 6079',
    'editor.allureId': 'Allure ID',
    'editor.allureIdPlaceholder': 'Example: 12345',
    'editor.sectionExpand': 'Expand section',
    'editor.sectionCollapse': 'Collapse section',

    'settings.title': 'Settings',
    'settings.close': 'Close',
    'settings.tab.atlassian': 'Atlassian Sync',
    'settings.tab.appearance': 'Appearance',
    'settings.loading': 'Loading…',
    'settings.saved': 'Saved to OS keychain',
    'settings.saveError': 'Failed to save. Try again.',
    'settings.atlassianTitle': 'Atlassian Sync',
    'settings.baseUrl': 'Atlassian base URL',
    'settings.login': 'Atlassian login',
    'settings.password': 'Password',
    'settings.passwordStored': 'stored',
    'settings.passwordPlaceholder': '•••••• (click the eye to reveal or enter a new value to replace)',
    'settings.hide': 'Hide',
    'settings.show': 'Show',
    'settings.hidePassword': 'Hide password',
    'settings.showPassword': 'Show password',
    'settings.securityHint': 'Login and base URL are stored in .settings.json inside the repository, while the secret is kept in the OS secure storage.',
    'settings.save': 'Save',
    'settings.appearanceTitle': 'Appearance',
    'settings.language': 'Interface language',
    'settings.theme': 'Theme',
    'settings.languageHint': 'Universal UI copy switches languages without modifying the test content itself.',
    'settings.themeHint': 'Dark theme applies across the editor and dialogs.',
    'settings.language.ru': 'Russian',
    'settings.language.en': 'English',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',

    'defaults.newFolder': 'New Folder',
    'defaults.newCase': 'New Case',
    'defaults.firstStep': 'Step 1',
    'defaults.sharedStep': 'Shared Step',
})

Object.assign(messages.ru, {
    'details.description': 'Описание',
    'details.objective': 'Цель теста',
    'details.preconditions': 'Предусловия',
    'details.view': 'Вид:',
    'details.preview': 'Предпросмотр',
    'details.raw': 'Исходный текст',
    'details.togglePreview': 'Переключить режим просмотра',

    'steps.title': 'Шаги',
    'steps.view': 'Вид:',
    'steps.previewAll': 'Предпросмотр всего',
    'steps.rawAll': 'Исходный текст всего',
    'steps.add': '+ Добавить шаг',
    'steps.apply': 'Применить',
    'steps.emptyTitle': 'Шагов пока нет',
    'steps.emptyText': 'Добавьте первый шаг и начните собирать действие, данные и ожидаемый результат.',
    'steps.addFirst': '+ Добавить первый шаг',
    'steps.saveAsShared': 'Сохранить как общий',
    'steps.clone': 'Клонировать шаг',
    'steps.addBelow': 'Добавить шаг ниже',
    'steps.remove': 'Удалить шаг',
    'steps.openShared': 'Открыть общий шаг',
    'steps.sharedMissing': 'Общий шаг не найден',
    'steps.sharedTitle': 'Общий: {name}',
    'steps.stepNumber': 'Шаг {index}',
    'steps.sharedStepsCount': 'Шагов: {count}',
    'steps.brokenLink': 'Ссылка сломана',
    'steps.sharedExportHint': 'Этот шаг разворачивается из общей библиотеки при экспорте и синхронизации.',
    'steps.sharedMissingHint': 'Связанный общий шаг больше не существует в библиотеке.',
    'steps.dragToReorder': 'Перетащите для изменения порядка',
    'steps.insertLink': 'Вставить ссылку на {kind}',
    'steps.action': 'Действие',
    'steps.data': 'Данные',
    'steps.expected': 'Ожидаемый результат',
    'steps.blocks': 'Блоки: {count}',
    'steps.files': 'Файлы: {count}',
    'steps.more': 'Ещё',
    'steps.addBlock': 'Добавить блок',
    'steps.sharedRef': 'Общая ссылка',
    'steps.missing': 'Отсутствует',

    'markdown.sharedLabel': 'Общий: {name}',
    'markdown.testLabel': 'Тест: {name}',
    'markdown.togglePreview': 'Переключить предпросмотр',
    'markdown.noSuggestions': 'Подсказок нет',
    'markdown.noSourceStep': 'Нет шага на стороне {label}',
    'markdown.step': 'Шаг {index}',
    'markdown.preview': 'Предпросмотр',
    'markdown.raw': 'Исходный текст',
    'markdown.action': 'Действие',
    'markdown.data': 'Данные',
    'markdown.expected': 'Ожидаемый результат',
    'markdown.wholeField': 'Целое поле',
    'markdown.stage.owner': '1. Тест',
    'markdown.stage.step': '2. Шаг',
    'markdown.stage.field': '3. Поле',
    'markdown.stage.part': '4. Part',

    'shared.title': 'Общие шаги',
    'shared.new': '+ Новый общий',
    'shared.total': 'всего',
    'shared.inUse': 'используется',
    'shared.broken': 'битых',
    'shared.search': 'Поиск по библиотеке',
    'shared.searchPlaceholder': 'Название или текст шага',
    'shared.sort': 'Сортировка',
    'shared.filter.all': 'Все',
    'shared.filter.used': 'Используются',
    'shared.filter.unused': 'Не используются',
    'shared.filter.broken': 'Битые ссылки',
    'shared.sort.usage': 'Сначала самые используемые',
    'shared.sort.name': 'По названию',
    'shared.sort.broken': 'Сначала с битыми ссылками',
    'shared.emptyLibrary': 'Библиотека пуста. Создайте первый общий шаг и переиспользуйте его в кейсах.',
    'shared.emptyFiltered': 'По текущему поиску и фильтрам ничего не найдено.',
    'shared.showing': 'Показано {visible} из {total}',
    'shared.selectToEdit': 'Выберите общий шаг, чтобы редактировать его.',
    'shared.name': 'Название общего шага',
    'shared.namePlaceholder': 'Название общего шага',
    'shared.insertIntoCase': 'Вставить в кейс',
    'shared.delete': 'Удалить',
    'shared.usageTitle': 'Использования и обратные ссылки',
    'shared.usageEmpty': 'Этот общий шаг пока нигде не используется.',
    'shared.usageKindShared': 'Использует общий шаг',
    'shared.usageKindRef': 'Ссылка',
    'shared.noBrokenRefs': 'Битых ссылок нет',
    'shared.brokenRefs': 'Битых ссылок: {count}',
    'shared.stepsCount': 'Шаги: {count}',
    'shared.usagesCount': 'Использований: {count}',

    'params.tags': 'Теги',
    'params.parameters': 'Параметры',
    'params.noParameters': 'Параметров пока нет.',
    'params.paramNamePlaceholder': 'Имя параметра',
    'params.paramValuePlaceholder': 'Значение',
    'params.addParameters': 'Добавить параметры',
    'params.addParam': '+ Добавить параметр',
    'params.create': 'Создать',
    'params.addTagPlaceholder': 'Добавить тег…',

    'attachments.title': 'Вложения',
    'attachments.upload': '+ Загрузить',
    'attachments.uploading': 'Загрузка…',
    'attachments.none': 'Вложений пока нет.',
    'attachments.remove': 'Удалить вложение',
    'attachments.stepTitle': 'Файлы шага',
    'attachments.stepNone': 'Файлов нет.',
    'attachments.removeFile': 'Удалить файл',

    'preview.closeDialog': 'Закрыть диалог',
    'preview.step': 'Шаг {index}',
    'preview.noSideStep': 'Нет шага на стороне {label}',
    'preview.local': 'Локально',
    'preview.remote': 'Удалённо',
    'preview.localPublish': 'Локальная публикация',
    'preview.action': 'Действие',
    'preview.data': 'Данные',
    'preview.expected': 'Ожидаемый результат',
})

Object.assign(messages.en, {
    'details.description': 'Description',
    'details.objective': 'Test Objective',
    'details.preconditions': 'Preconditions',
    'details.view': 'View:',
    'details.preview': 'Preview',
    'details.raw': 'Raw',
    'details.togglePreview': 'Toggle preview',

    'steps.title': 'Steps',
    'steps.view': 'View:',
    'steps.previewAll': 'Preview all',
    'steps.rawAll': 'Raw all',
    'steps.add': '+ Add step',
    'steps.apply': 'Apply',
    'steps.emptyTitle': 'No steps yet',
    'steps.emptyText': 'Add the first step and start composing action, data and expected result.',
    'steps.addFirst': '+ Add first step',
    'steps.saveAsShared': 'Save as shared',
    'steps.clone': 'Clone step',
    'steps.addBelow': 'Add step below',
    'steps.remove': 'Remove step',
    'steps.openShared': 'Open shared',
    'steps.sharedMissing': 'Missing shared step',
    'steps.sharedTitle': 'Shared: {name}',
    'steps.stepNumber': 'Step {index}',
    'steps.sharedStepsCount': 'Steps: {count}',
    'steps.brokenLink': 'Broken link',
    'steps.sharedExportHint': 'This step expands from the shared library on export and sync.',
    'steps.sharedMissingHint': 'The referenced shared step no longer exists in the library.',
    'steps.dragToReorder': 'Drag to reorder',
    'steps.insertLink': 'Insert {kind} link',
    'steps.action': 'Action',
    'steps.data': 'Data',
    'steps.expected': 'Expected',
    'steps.blocks': 'Blocks: {count}',
    'steps.files': 'Files: {count}',
    'steps.more': 'More',
    'steps.addBlock': 'Add block',
    'steps.sharedRef': 'Shared ref',
    'steps.missing': 'Missing',

    'markdown.sharedLabel': 'Shared: {name}',
    'markdown.testLabel': 'Test: {name}',
    'markdown.togglePreview': 'Toggle preview',
    'markdown.noSuggestions': 'No suggestions',
    'markdown.noSourceStep': 'No {label} step',
    'markdown.step': 'Step {index}',
    'markdown.preview': 'Preview',
    'markdown.raw': 'Raw',
    'markdown.action': 'Action',
    'markdown.data': 'Data',
    'markdown.expected': 'Expected',
    'markdown.wholeField': 'Whole field',
    'markdown.stage.owner': '1. Test',
    'markdown.stage.step': '2. Step',
    'markdown.stage.field': '3. Field',
    'markdown.stage.part': '4. Part',

    'shared.title': 'Shared steps',
    'shared.new': '+ New shared',
    'shared.total': 'total',
    'shared.inUse': 'in use',
    'shared.broken': 'broken',
    'shared.search': 'Search library',
    'shared.searchPlaceholder': 'Name or step text',
    'shared.sort': 'Sort',
    'shared.filter.all': 'All',
    'shared.filter.used': 'In use',
    'shared.filter.unused': 'Unused',
    'shared.filter.broken': 'Broken refs',
    'shared.sort.usage': 'Most used',
    'shared.sort.name': 'Name',
    'shared.sort.broken': 'Broken refs',
    'shared.emptyLibrary': 'The library is empty. Create the first shared step and reuse it across cases.',
    'shared.emptyFiltered': 'No shared steps match the current search and filters.',
    'shared.showing': 'Showing {visible} of {total}',
    'shared.selectToEdit': 'Select a shared step to edit it.',
    'shared.name': 'Shared step name',
    'shared.namePlaceholder': 'Shared step name',
    'shared.insertIntoCase': 'Insert into case',
    'shared.delete': 'Delete',
    'shared.usageTitle': 'Usages and backlinks',
    'shared.usageEmpty': 'This shared step is not used anywhere yet.',
    'shared.usageKindShared': 'Uses shared',
    'shared.usageKindRef': 'Ref',
    'shared.noBrokenRefs': 'No broken refs',
    'shared.brokenRefs': 'Broken refs: {count}',
    'shared.stepsCount': 'Steps: {count}',
    'shared.usagesCount': 'Usages: {count}',

    'params.tags': 'Tags',
    'params.parameters': 'Parameters',
    'params.noParameters': 'No parameters yet.',
    'params.paramNamePlaceholder': 'Param name',
    'params.paramValuePlaceholder': 'Value',
    'params.addParameters': 'Add parameters',
    'params.addParam': '+ Add param',
    'params.create': 'Create',
    'params.addTagPlaceholder': 'Add tag…',

    'attachments.title': 'Attachments',
    'attachments.upload': '+ Upload',
    'attachments.uploading': 'Uploading…',
    'attachments.none': 'No attachments yet.',
    'attachments.remove': 'Remove attachment',
    'attachments.stepTitle': 'Step attachments',
    'attachments.stepNone': 'No files.',
    'attachments.removeFile': 'Remove file',

    'preview.closeDialog': 'Close dialog',
    'preview.step': 'Step {index}',
    'preview.noSideStep': 'No {label} step',
    'preview.local': 'Local',
    'preview.remote': 'Remote',
    'preview.localPublish': 'Local publish',
    'preview.action': 'Action',
    'preview.data': 'Data',
    'preview.expected': 'Expected',
})

Object.assign(messages.ru, {
    'import.title': 'Импорт из Zephyr',
    'import.subtitle': 'Назначение: {label}',
    'import.scope': 'Область',
    'import.mode.project': 'Проект',
    'import.mode.folder': 'Папка',
    'import.mode.keys': 'Набор ключей',
    'import.projectKey': 'Ключ проекта',
    'import.folderPath': 'Путь папки',
    'import.keysOrIds': 'Ключи или ID Zephyr',
    'import.rawQuery': 'Переопределение запроса',
    'import.rawQueryPlaceholder': 'Необязательно. Например: projectKey = "PROD" AND folder = "/CORE/Auth"',
    'import.maxResults': 'Максимум результатов',
    'import.mirrorFolders': 'Повторять структуру папок Zephyr',
    'import.scopeHint': 'Области проекта и папки используют поиск Zephyr. Режим набора ключей запрашивает каждый кейс напрямую.',
    'import.loadPreview': 'Загрузить preview',
    'import.loadingPreview': 'Загрузка preview...',
    'import.close': 'Закрыть',
    'import.previewEmptyTitle': 'Preview',
    'import.previewEmptyText': 'Выберите область импорта, загрузите preview, затем проверьте различия до того, как что-то коснётся локальных кейсов.',
    'import.previewTitle': 'Preview',
    'import.query': 'Запрос',
    'import.directLookup': 'прямой поиск по ключам',
    'import.total': 'Всего {count}',
    'import.new': 'Новые {count}',
    'import.updates': 'Обновления {count}',
    'import.conflicts': 'Конфликты {count}',
    'import.unchanged': 'Без изменений {count}',
    'import.conflictsTitle': 'Сначала проверьте конфликты',
    'import.conflictsHint': 'Удалённые кейсы совпали с локальными. Проверьте их до запуска замены.',
    'import.onlyConflicts': 'Только конфликты',
    'import.jumpFirstConflict': 'Перейти к первому конфликту',
    'import.replaceCount': 'Заменить {count}',
    'import.skipCount': 'Пропустить {count}',
    'import.mergeLaterCount': 'Объединить позже {count}',
    'import.moreConflicts': '+ ещё конфликтов: {count}',
    'import.reviewFilters': 'Фильтры просмотра',
    'import.filter.all': 'Все {count}',
    'import.filter.new': 'Новые {count}',
    'import.filter.updates': 'Обновления {count}',
    'import.filter.conflicts': 'Конфликты {count}',
    'import.filter.unchanged': 'Без изменений {count}',
    'import.showUnchanged': 'Показывать без изменений',
    'import.hidden': 'Скрыто {count}',
    'import.collapsedUnchanged': 'Элементов без изменений скрыто: {count}, чтобы было проще проверять пачку.',
    'import.emptyFound': 'Тест-кейсы не найдены',
    'import.emptyFoundText': 'Preview завершился успешно, но Zephyr вернул пустой набор для этой области.',
    'import.emptyFilters': 'Нет элементов под текущие фильтры',
    'import.emptyFiltersText': 'Измените фильтры статуса, чтобы продолжить проверку этой пачки.',
    'import.shown': 'Показано {count}',
    'import.resetFilters': 'Сбросить фильтры',
    'import.apply': 'Применить импорт',
    'import.applying': 'Применение...',
    'import.previewError': 'Не удалось загрузить preview импорта',
    'import.applyError': 'Не удалось применить импорт',
    'import.localTest': 'Локальный кейс',
    'import.localFolder': 'Локальная папка',
    'import.importInto': 'Импортировать в',
    'import.matches': 'Совпадений',
    'import.willBeCreated': 'Будет создан',
    'import.conflictStrategy': 'Стратегия конфликта',
    'import.strategy.replace': 'Заменить локальный',
    'import.strategy.skip': 'Пропустить',
    'import.strategy.mergeLater': 'Объединить локально позже',
    'import.status.new': 'Новый',
    'import.status.update': 'Обновление',
    'import.status.conflict': 'Конфликт',
    'import.status.unchanged': 'Без изменений',

    'publish.title': 'Публикация локального в Zephyr',
    'publish.subtitle': 'Область: {label}',
    'publish.dryRun': 'Dry-run',
    'publish.dryRunHint': 'Этот preview сравнивает локальные кейсы с текущим состоянием Zephyr и готовит replace-публикацию. Перед первой записью создаётся локальный снимок, после выполнения сохраняется лог.',
    'publish.confirmation': 'Подтверждение',
    'publish.confirmationHint': 'Введите PUBLISH, чтобы включить массовую replace-операцию.',
    'publish.loadDryRun': 'Загрузить dry-run',
    'publish.loadingPreview': 'Загрузка preview...',
    'publish.close': 'Закрыть',
    'publish.previewEmptyTitle': 'Preview',
    'publish.previewEmptyText': 'Сначала загрузите dry-run, чтобы проверить создание, обновление и заблокированные элементы.',
    'publish.previewTitle': 'Preview публикации',
    'publish.scopeSummary': 'Кейсов в области: {total}, выбрано к публикации: {selected}',
    'publish.create': 'Создать {count}',
    'publish.update': 'Обновить {count}',
    'publish.skip': 'Пропустить {count}',
    'publish.blocked': 'Заблокировано {count}',
    'publish.blockedTitle': 'Сначала проверьте заблокированные элементы',
    'publish.blockedHint': 'Эти элементы нельзя опубликовать, пока не сняты блокировки.',
    'publish.onlyBlocked': 'Только заблокированные',
    'publish.jumpFirstBlocked': 'Перейти к первому заблокированному',
    'publish.moreBlocked': '+ ещё заблокированных: {count}',
    'publish.reviewFilters': 'Фильтры просмотра',
    'publish.filter.all': 'Все {count}',
    'publish.filter.create': 'Создать {count}',
    'publish.filter.update': 'Обновить {count}',
    'publish.filter.blocked': 'Заблокировано {count}',
    'publish.filter.skip': 'Пропустить {count}',
    'publish.selectedOnly': 'Только выбранные',
    'publish.showSkipped': 'Показывать пропущенные',
    'publish.hidden': 'Скрыто {count}',
    'publish.collapsedSkipped': 'Пропущенных элементов скрыто: {count}, чтобы публикацию было проще проверять.',
    'publish.emptyFilters': 'Нет элементов под текущие фильтры',
    'publish.emptyFiltersText': 'Измените фильтры, чтобы продолжить проверку этой пачки публикации.',
    'publish.shown': 'Показано {count}',
    'publish.selected': 'Выбрано {count}',
    'publish.resetFilters': 'Сбросить фильтры',
    'publish.run': 'Публиковать в Zephyr',
    'publish.running': 'Публикация...',
    'publish.previewError': 'Не удалось построить preview публикации',
    'publish.applyError': 'Не удалось опубликовать в Zephyr',
    'publish.newCase': 'Новый тест-кейс',
    'publish.include': 'Включить в публикацию',
    'publish.status.create': 'Создать',
    'publish.status.update': 'Обновить',
    'publish.status.blocked': 'Заблокировано',
    'publish.status.skip': 'Пропустить',
})

Object.assign(messages.en, {
    'import.title': 'Import From Zephyr',
    'import.subtitle': 'Destination: {label}',
    'import.scope': 'Scope',
    'import.mode.project': 'Project',
    'import.mode.folder': 'Folder',
    'import.mode.keys': 'Key set',
    'import.projectKey': 'Project key',
    'import.folderPath': 'Folder path',
    'import.keysOrIds': 'Zephyr keys or ids',
    'import.rawQuery': 'Raw query override',
    'import.rawQueryPlaceholder': 'Optional. Example: projectKey = "PROD" AND folder = "/CORE/Auth"',
    'import.maxResults': 'Max results',
    'import.mirrorFolders': 'Mirror Zephyr folders',
    'import.scopeHint': 'Project and folder scopes use the Zephyr search API. Key-set scope fetches each case directly.',
    'import.loadPreview': 'Load preview',
    'import.loadingPreview': 'Loading preview...',
    'import.close': 'Close',
    'import.previewEmptyTitle': 'Preview',
    'import.previewEmptyText': 'Select the import scope, load the preview, then review diffs before anything touches local tests.',
    'import.previewTitle': 'Preview',
    'import.query': 'Query',
    'import.directLookup': 'direct key lookup',
    'import.total': 'Total {count}',
    'import.new': 'New {count}',
    'import.updates': 'Updates {count}',
    'import.conflicts': 'Conflicts {count}',
    'import.unchanged': 'Unchanged {count}',
    'import.conflictsTitle': 'Conflicts to review first',
    'import.conflictsHint': 'Remote cases matched local tests. Review them before running replace.',
    'import.onlyConflicts': 'Only conflicts',
    'import.jumpFirstConflict': 'Jump to first conflict',
    'import.replaceCount': 'Replace {count}',
    'import.skipCount': 'Skip {count}',
    'import.mergeLaterCount': 'Merge later {count}',
    'import.moreConflicts': '+ {count} more conflicts in this preview',
    'import.reviewFilters': 'Review filters',
    'import.filter.all': 'All {count}',
    'import.filter.new': 'New {count}',
    'import.filter.updates': 'Updates {count}',
    'import.filter.conflicts': 'Conflicts {count}',
    'import.filter.unchanged': 'Unchanged {count}',
    'import.showUnchanged': 'Show unchanged',
    'import.hidden': '{count} hidden',
    'import.collapsedUnchanged': '{count} unchanged items are collapsed to keep the review focused.',
    'import.emptyFound': 'No test cases found',
    'import.emptyFoundText': 'The preview finished successfully, but Zephyr returned an empty set for this scope.',
    'import.emptyFilters': 'No items match the current filters',
    'import.emptyFiltersText': 'Adjust the status filters to continue reviewing this batch.',
    'import.shown': '{count} shown',
    'import.resetFilters': 'Reset filters',
    'import.apply': 'Apply import',
    'import.applying': 'Applying...',
    'import.previewError': 'Failed to load import preview',
    'import.applyError': 'Failed to apply import',
    'import.localTest': 'Local test',
    'import.localFolder': 'Local folder',
    'import.importInto': 'Import into',
    'import.matches': 'Matches',
    'import.willBeCreated': 'Will be created',
    'import.conflictStrategy': 'Conflict strategy',
    'import.strategy.replace': 'Replace local',
    'import.strategy.skip': 'Skip',
    'import.strategy.mergeLater': 'Merge locally later',
    'import.status.new': 'New',
    'import.status.update': 'Update',
    'import.status.conflict': 'Conflict',
    'import.status.unchanged': 'Unchanged',

    'publish.title': 'Publish Local -> Zephyr',
    'publish.subtitle': 'Scope: {label}',
    'publish.dryRun': 'Dry-run',
    'publish.dryRunHint': 'This preview compares local tests with current Zephyr state, then prepares a replace publish. A local snapshot is created before the first write, and a publish log is saved after the run.',
    'publish.confirmation': 'Confirmation',
    'publish.confirmationHint': 'Type PUBLISH to enable the mass replace action.',
    'publish.loadDryRun': 'Load dry-run',
    'publish.loadingPreview': 'Loading preview...',
    'publish.close': 'Close',
    'publish.previewEmptyTitle': 'Preview',
    'publish.previewEmptyText': 'Load the dry-run first to review create, update and blocked items.',
    'publish.previewTitle': 'Publish preview',
    'publish.scopeSummary': '{total} tests in scope, {selected} selected to publish',
    'publish.create': 'Create {count}',
    'publish.update': 'Update {count}',
    'publish.skip': 'Skip {count}',
    'publish.blocked': 'Blocked {count}',
    'publish.blockedTitle': 'Blocked items to review first',
    'publish.blockedHint': 'These items cannot be published until their blockers are resolved.',
    'publish.onlyBlocked': 'Only blocked',
    'publish.jumpFirstBlocked': 'Jump to first blocked',
    'publish.moreBlocked': '+ {count} more blocked items in this preview',
    'publish.reviewFilters': 'Review filters',
    'publish.filter.all': 'All {count}',
    'publish.filter.create': 'Create {count}',
    'publish.filter.update': 'Update {count}',
    'publish.filter.blocked': 'Blocked {count}',
    'publish.filter.skip': 'Skip {count}',
    'publish.selectedOnly': 'Selected only',
    'publish.showSkipped': 'Show skipped',
    'publish.hidden': '{count} hidden',
    'publish.collapsedSkipped': '{count} skipped items are collapsed to keep the publish review focused.',
    'publish.emptyFilters': 'No items match the current filters',
    'publish.emptyFiltersText': 'Adjust the filters to continue reviewing this publish batch.',
    'publish.shown': '{count} shown',
    'publish.selected': '{count} selected',
    'publish.resetFilters': 'Reset filters',
    'publish.run': 'Publish to Zephyr',
    'publish.running': 'Publishing...',
    'publish.previewError': 'Failed to build publish preview',
    'publish.applyError': 'Failed to publish to Zephyr',
    'publish.newCase': 'New test case',
    'publish.include': 'Include in publish run',
    'publish.status.create': 'Create',
    'publish.status.update': 'Update',
    'publish.status.blocked': 'Blocked',
    'publish.status.skip': 'Skip',
})

export type MessageKey = keyof typeof messages.en

export function getStoredLocale(): UiLocale {
    if (typeof window === 'undefined') return 'ru'
    const stored = window.localStorage.getItem(LOCALE_STORAGE_KEY)
    return stored === 'en' || stored === 'ru' ? stored : 'ru'
}

export function getStoredThemeMode(): UiThemeMode {
    if (typeof window === 'undefined') return 'dark'
    const stored = window.localStorage.getItem(THEME_STORAGE_KEY)
    return stored === 'light' || stored === 'dark' ? stored : 'dark'
}

function formatMessage(template: string, params?: Record<string, string | number>) {
    if (!params) return template
    return template.replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? ''))
}

export function translate(
    key: MessageKey,
    params?: Record<string, string | number>,
    locale: UiLocale = getStoredLocale()
) {
    const template = messages[locale][key] ?? messages.en[key] ?? key
    return formatMessage(template, params)
}

type PreferencesContextValue = {
    locale: UiLocale
    setLocale(locale: UiLocale): void
    themeMode: UiThemeMode
    setThemeMode(mode: UiThemeMode): void
    t(key: MessageKey, params?: Record<string, string | number>): string
}

const PreferencesContext = React.createContext<PreferencesContextValue | null>(null)

export function UiPreferencesProvider({ children }: { children: React.ReactNode }) {
    const [locale, setLocaleState] = React.useState<UiLocale>(() => getStoredLocale())
    const [themeMode, setThemeModeState] = React.useState<UiThemeMode>(() => getStoredThemeMode())

    React.useEffect(() => {
        document.documentElement.lang = locale
        document.documentElement.dataset.theme = themeMode
        window.localStorage.setItem(LOCALE_STORAGE_KEY, locale)
        window.localStorage.setItem(THEME_STORAGE_KEY, themeMode)
    }, [locale, themeMode])

    const value = React.useMemo<PreferencesContextValue>(
        () => ({
            locale,
            setLocale: setLocaleState,
            themeMode,
            setThemeMode: setThemeModeState,
            t: (key, params) => translate(key, params, locale),
        }),
        [locale, themeMode]
    )

    return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}

export function useUiPreferences() {
    const context = React.useContext(PreferencesContext)
    if (!context) throw new Error('useUiPreferences must be used within <UiPreferencesProvider/>')
    return context
}
